driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["winrm_port"] %>
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>

provisioner:
  name: chef_zero

platforms:
  - name: windows-latest

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - path: test/integration/default
  - name: versioned
    run_list:
      - recipe[test::versioned]
    verifier:
      inspec_tests:
        - path: test/integration/versioned
