source 'https://rubygems.org'

gem 'rake', '~> 11.2.2'
gem 'foodcritic', '~> 6.3.0'
gem 'rubocop', '= 0.39.0'
gem 'kitchen-inspec', '~> 0.14'
gem 'test-kitchen', '~> 1.6'
gem 'berkshelf', '~> 4.0'
gem 'httparty'
gem 'rspec'
