source 'https://rubygems.org'

gem 'rake'
gem 'foodcritic', '>= 7.0'
gem 'rubocop', '= 0.39.0'
gem 'inspec', '>= 0.17.1'
gem 'kitchen-inspec'
gem 'test-kitchen'
gem 'berkshelf', '~> 4.3.5'
gem 'stove'
