source 'https://rubygems.org'

gem 'rake'
gem 'foodcritic', '>= 7.1.0'
gem 'rubocop', '= 0.39.0'
gem 'inspec', '>= 1.0.0'
gem 'kitchen-inspec'
gem 'test-kitchen'
gem 'berkshelf', '~> 5.1.0'
gem 'stove'
