name             'appveyor-ci'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs AppVeyor Agent & Triggers Deployment'
issues_url       'https://github.com/sous-chefs/appveyor-ci/issues'
source_url       'https://github.com/sous-chefs/appveyor-ci'
version          '0.2.4'
chef_version     '>= 13.0'

supports 'windows'
